[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "latency-api"
version = "0.1.0"
dependencies = [
  "fastapi==0.115.0",
  "uvicorn[standard]==0.32.0",
  "numpy==2.2.4",
  "pandas==2.2.3",
  "python-multipart==0.0.9",
]
